# Generated by Django 4.2rc1 on 2025-01-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponse',
            name='headers',
            field=models.JSONField(default=None),
        ),
    ]
