# Generated by Django 4.2rc1 on 2025-01-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_requestresponse_headers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestresponse',
            unique_together=set(),
        ),
    ]
